name = "cloudflare-slack-bot"
main = "src/index.ts"
compatibility_date = "2023-02-18"

[vars]
# The necessary secrets are:
# - SLACK_SIGNING_SECRET
# - SLACK_BOT_TOKEN
# - SLACK_APP_TOKEN
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
