name = "cloudflare-slack-bot"
main = "src/index.ts"
compatibility_date = "2023-02-18"

[vars]
BOT_ID="U02RWTNJFPS"

# The necessary secrets are:
# - SLACK_BOT_TOKEN
# - SLACK_VERIFIACTION_CODE
# Run `echo <VALUE> | yarn wrangler secret put <NAME>` for each of these
