name: Deployment

concurrency: production

on:
  push:
    # branches:
    #   - main
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: Target ref to deploy
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ inputs?.ref ?? '' }}
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
