name: Deployment

concurrency: production

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true
  deployment:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.deployment.environment }}
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            // deployment: payload.deployment.environment
            console.log(' PAYLOAD', JSON.stringify(context.payload ?? {}, null, 2));
      - run: echo "${{ github.event }}"
      - run: echo "${{ github.event.inputs }}"
      - run: echo "${{ github.event.inputs.environment }}"
      - run: echo "${{ github.event_name }}"
      - uses: actions/checkout@v3
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
