name: Deployment

concurrency: production

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy
        type: environment
        required: true
        default: staging
  deployment:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.deployment.environment || github.event.inputs.environment || 'production' }}
    steps:
      - run: echo "${{ jobs.deploy.environment }}"
      - run: echo "${{ job.environment }}"
      - uses: actions/checkout@v3
      - name: Deploy to ${{ jobs.deploy.environment }}
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
