name: Deployment

concurrency: production

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(' EVENT', JSON.stringify(context.event ?? {}));
            console.log(' PAYLOAD', JSON.stringify(context.payload ?? {}));
            console.log(' REPO', JSON.stringify(context.repo ?? {}));
      - uses: actions/checkout@v3
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
