name: Deployment

concurrency: production

on:
  push:
    branches:
      - main
  # workflow_dispatch:
  deployment:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            console.log(' EVENT', JSON.stringify(context.event ?? {}, null, 2));
            console.log(' PAYLOAD', JSON.stringify(context.payload ?? {}, null, 2));
            console.log(' REPO', JSON.stringify(context.repo ?? {}), null, 2);
      # - run: echo "${{ JSON.stringify(github, null, 2) }}"
      # - run: echo "${{ JSON.stringify(vars, null, 2) }}"
      # - run: echo "${{ JSON.stringify(event, null, 2) }}"
      - run: echo "${{ github.event.environment }}"
      - run: echo "${{ github.event_name }}"
      - uses: actions/checkout@v3
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
