name: Deployment

concurrency: production

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true
  deployment:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.deployment.environment || github.event.inputs.environment || 'production' }}
    steps:
      - run: echo "${{ github.event.deployment.environment }}"
      - run: echo "${{ github.event.inputs.environment }}"
      - run: echo "${{ github.event.deployment.environment || github.event.inputs.environment || 'production' }}"
      - uses: actions/checkout@v3
      - uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
